# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://gc.scyted.tv'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 


# Title of the Site
title: Game Changer Fan Theories
# Description of the Site
description: Theories, Findings, etc.
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Game Changer, Dropout, Game Changer Dropout
# URL for the Image of custom Favicon
favicon-url: https://cdn.scyted.tv/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.scyted.tv/website-assets/website/gc-hero-image.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 
facebook_username:
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  
youtube_channel_id: UCBClJ5Q0LTCRtlEYE1oB6Pg
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: G-54KSRP46MF

# Disqus
disqus-shortname: game-changer-fan-theories

# Name of the Author
author-name: 
# URL for the Image of the Author
author-image: 
# 60 Words About the Author
author-about: 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:

  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""

  -
    scope:
      type: 'pages'
    values:
      layout: page
  -

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
